# Generated by Django 3.1 on 2020-08-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
